language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -U pip setuptools
  - pip install -U tox tox-venv tox-travis
  - pip install -U coveralls

script:
  - tox

after_success:
  -coveralls
